import hanabi_deck

class Game:
    """
    Class representing the Hanabi Game.

    This class handles all interactions between players, cards, the board,
        the deck, and the discard pile. 

    By separating the game from the server's code, it is simpler to support
        multiple games on the server at a time using some sort of game ID.
    """

    def __init__(self, players, id=None, difficulty=0, password=None):
        """
        Constructor for game.

        This method effectively 'sets up' a game of Hanabi. It 
            - creates the deck
            - deals the hands

        :param: players - list of Player objects
        :param: difficulty - number representing difficulty level. Default to 0
            Difficulties:
                **Insert description of difficulties when we figure that out.

        Support for future support of multiple games
            :param: password - string password for game, optional
            :param: id - game uuid. Identifier of games on server
                Will be required, generated by server when new game is created.
        """
        self.deck = hanabi_deck.Deck()


    def play(self, card):
        pass

    def draw(self):
        """
        """
        return self.deck.pop()